### ISSUE TITLE
CCPP TechDoc Overview needs update wrt suites

### ISSUE THREAD

**Issue by ligiabernardet** [NCAR/ccpp-doc#30]
The CCPP TechDoc Overview needs to be updated to correctly reflect the suites that will be part of the CCPP v5.0 release. 

- Reference to the _no_nsst suites should be removed. 
- Suite RRFS_v1beta may change per the SRW App leads with one or more of the following 
-- Suite name change to RRFS_v1alpha
-- Sfc layer: change from MYNN to GFS
--LSM: change from NoahMP to Noah

In addition, documentation should list the target resolution for teh suites (RRFS - CAM scales, others MRW-S2S scales).

Need to hear back from SRW App leads before proceeding.

**Comment by climbfuji** [comment]
Can this be done now that suite `RRFS_v1alpha` is finalized?

**Comment by ligiabernardet** [comment]
Yes, we now have all the information we need. @JulieSchramm and I will make sure it gets done before the deadline.

**Comment by ligiabernardet** [comment]
This update has already been committed.
