### ISSUE TITLE
Update of how (from where) to run ccpp_prebuild.py

### ISSUE THREAD

**Issue by DomHeinzeller** [NCAR/ccpp-doc#31]
As described in detail in https://github.com/ufs-community/ufs-weather-model/issues/135, the call to `ccpp_prebuild.py` has been moved from the top-level ufs-weather-model repository to subdirectory FV3.

We initially wanted to push back on this change and revert it. However, given that we "taught" the new way to run `ccpp_prebuild.py` manually at the UFS MRW tutorial, we should instead change the documentation and keep it as is.

**Comment by JulieSchramm** [comment]
Would these changes go to master or one of the release branches, or both?

**Comment by ligiabernardet** [comment]
The CCPP Tech documentation does not cover details of the build for the UFS
Weather Model and therefore does not need to change to reflect this PR.
The UFS Weather Model build is described in the repo wiki page.

**Comment by climbfuji** [comment]
I think this can be closed?
