### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by ligiabernardet** [NCAR/ccpp-doc#39]
The CCPP team would like to rename the "master" branch to "main" to be sensitive to anti-racism practices.
Here is an article about this topic: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/.
Here is the GitHub page with steps for the renaming: https://github.com/github/renaming.

**Comment by JulieSchramm** [comment]
Renamed master to main.
