### ISSUE TITLE
Keep d*3dt instructions online

### ISSUE THREAD

**Issue by ericaligo-NOAA** [NCAR/ccpp-doc#46]
It is expected that many users still have the need for putting d*3dt output into history files, and it is suggested that instructions on the method for doing this be available online.

**Comment by ligiabernardet** [comment]
@ericaligo-NOAA  The old instructions can be found in older versions of ccpp-doc, such as at https://ccpp-techdoc.readthedocs.io/en/v5.0.0/ParamSpecificOutput.html. You can switch between versions of the doc in the lower right corner.

**Comment by ericaligo-NOAA** [comment]
Excellent! Thanks.
-------- Original message --------From: ligiabernardet ***@***.***> Date: 7/27/21  5:59 PM  (GMT-05:00) To: NCAR/ccpp-doc ***@***.***> Cc: ericaligo-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NCAR/ccpp-doc] Keep d*3dt instructions online (#46) 
@ericaligo-NOAA  The old instructions can be found in older versions of ccpp-doc, such as at https://ccpp-techdoc.readthedocs.io/en/v5.0.0/ParamSpecificOutput.html. You can switch between versions of the doc in the lower right corner.
