### ISSUE TITLE
Parts of CCPP documentation duplicate other documents

### ISSUE THREAD

**Issue by ligiabernardet** [NCAR/ccpp-doc#5]
A new documentation wiki has been stood up for the UFS weather model at https://github.com/ufs-community/ufs-weather-model/wiki. This duplicates part of the content of Chapters 7 and 9 of the CCPP Tech Doc, which should be updated to refer to this new source of information.

**Comment by climbfuji** [comment]
This needs to be addressed for the UFS release.

**Comment by ligiabernardet** [comment]
Done
