### ISSUE TITLE
Upcoming update of host model DDT variable names

### ISSUE THREAD

**Issue by climbfuji** [NCAR/ccpp-doc#54]
Section 6.3 in the technical documentation describes CCPP Variables in the SCM and UFS Atmosphere Host Models (https://ccpp-techdoc.readthedocs.io/en/latest/HostSideCoding.html).

There is a set of PRs for the ufs-weather-model that modifies where these data structures are stored and how they are named (see  https://github.com/ufs-community/ufs-weather-model/pull/1130 for the top-level ufs-weather-model PR). When these PR get merged, section 6.3 needs to be updated.

**Comment by ligiabernardet** [comment]
I have added this documentation request to https://github.com/NCAR/ccpp-doc/issues/63. So perhaps this issue can be closed? @mkavulich

**Comment by mkavulich** [comment]
Superseded by #63
