### ISSUE TITLE
Consistent description of CCPP metadata hooks in Fortran code

### ISSUE THREAD

**Issue by climbfuji** [NCAR/ccpp-doc#58]
We need to check that we use a consistent description of CCPP metadata hooks in Fortran code between the CCPP technical documentation, the scientific documentation (and ideally also in the Fortran code, although the latter doesn't matter because there are no errors).

Previously, we used
```
!> \section arg_table_foo_type Argument Table
!! \htmlinclude foo_type.html
!!
   type foo_type
```
but the CCPP framework doesn't care about `Argument Table` (and there is really no need or reason for it). The following works and should be used consistently across the board, most importantly in the CCPP v6 release of the scidoc and techdoc (because it will be in the CCPP paper this way):
```
!> \section arg_table_foo_type
!! \htmlinclude foo_type.html
!!
   type foo_type
```
It doesn't matter whether the Fortran code has the trailing `Argument Table` or not, it will simply be ignored. I just tested this again, and it works. This applies to both `ccpp_prebuild.py` and `capgen.py`, so we are good here.

**Comment by ligiabernardet** [comment]
@climbfuji What are the action items here? Change every occurrence of `\section arg_table_foo_type Argument Table` to `\section arg_table_foo_type` in both 1) theTech Doc and 2) the ccpp-physics *.F90 files?

Do you want to submit the PR to the ccpp-physics release/public-v6 branch?

Does any thing need to change in the SciDoc?

**Comment by climbfuji** [comment]
I believe that the scidoc changes have been made by @mzhangw already, so I added this to have her confirm (or if not, make the changes). 

The ccpp-physics file changes are optional, they need to be made at some point, but the presence of "Argument Table" doesn't bother the parser. I can make ccpp-physics changes, but only in about two weeks from now. This shouldn't hold up the creation/finalization of the v6 release branch or the SRW App release. We have other inconsistencies (use of local constants, ...) in ccpp-physics, too.

But definitely the techdoc needs to be changed.

**Comment by grantfirl** [comment]
Won't removing the "Argument Table" leave the argument table in the created HTML without a title?

**Comment by mzhangw** [comment]
Besides Grant's concern, in Doxygen world, there should be two arguments following \section command as it is stated [Doxygen's [manual];](https://www.doxygen.nl/manual/commands.html#cmdsection)
\section <section-name> (section title)
Creates a section with name <section-name>. The title of the section should be specified as the second argument of the \section command.

**Comment by mzhangw** [comment]
Besides Grant's concern, there should be two arguments following \section command as stated in Doxygen manual[https://www.doxygen.nl/manual/commands.html#cmdsection](url):

_**\section <section-name> (section title)**
Creates a section with name <section-name>. The title of the section should be specified as the second argument of the \section command._

**Comment by climbfuji** [comment]
> Besides Grant's concern, there should be two arguments following \section command as stated in Doxygen manual([link](https://www.doxygen.nl/manual/commands.html#cmdsection)):
> 
> _\section section-name (section title) Creates a section with name . **The title of the section should be specified as the second argument of the \section command**._

These are all good points that I haven't thought about. If we need to keep using
```
\section arg_table_foo_type Argument Table
```
then I will need to update the manuscript, and someone needs to modify the `capgen` parser to exit with an error if these arguments aren't there (and add a unit/doc test for it).

**Comment by climbfuji** [comment]
I changed the paper to match what was discussed here
